CREATE TABLE IF NOT EXISTS users
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
  age INT(11) NULL DEFAULT NULL COMMENT '年龄',
  email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
  point_count INT(11) NULL DEFAULT 0 COMMENT '积分',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS points
(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id BIGINT(20) NOT NULL COMMENT '用户Id',
  money BIGINT(20) NOT NULL COMMENT '消费钱',
  order_time TIMESTAMP NULL DEFAULT NULL COMMENT '时间',
  PRIMARY KEY (id)
);
