DROP TABLE IF EXISTS orders;

CREATE TABLE orders
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '订单名称',
  price INT(11) NULL DEFAULT NULL COMMENT '价格',
  user_id BIGINT(20) NOT NULL COMMENT '用户Id',
  PRIMARY KEY (id)
);