CREATE TABLE IF NOT EXISTS orders
(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '订单名称',
  price INT(11) NULL DEFAULT NULL COMMENT '价格',
  count INT(11) NULL DEFAULT NULL COMMENT '个数',
  order_time TIMESTAMP NULL DEFAULT NULL COMMENT '消费时间',
  user_id BIGINT(20) NOT NULL COMMENT '用户Id',
  PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS outbox
(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  order_type VARCHAR(10) NULL DEFAULT NULL COMMENT '订单类型-1新增，2删除',
  content VARCHAR(200) NULL DEFAULT NULL COMMENT '订单内容',
  sts VARCHAR(10) NULL DEFAULT NULL COMMENT '状态-1.新增，2.处理中，3.完成',
  PRIMARY KEY (id)
);